version: '3.9'
services:
  mqtt:
    container_name: mqtt-server
    image: ggfto/mosquitto:latest
    restart: always
    ports:
     - 1883:1883
     - 9001:9001
  # mqtt-client:
  #   container_name: mqtt-client
  #   image: ggfto/mqtt-client:latest
  #   restart: always
  #   ports:
  #     - 8180:8080
  #   environment:
  #     MQTT_SERVER: ${MQTT_SERVER}
  #     MQTT_PORT: ${MQTT_PORT}
  #     MQTT_CLIENTID: ${MQTT_CLIENTID}